# Generated by Django 5.0.2 on 2024-02-20 21:56

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("external_id", models.CharField(db_index=True, max_length=256)),
                ("category", models.CharField(max_length=256)),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=9)),
                (
                    "ratings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[
                                django.core.validators.MaxValueValidator(5),
                                django.core.validators.MinValueValidator(1),
                            ]
                        ),
                        size=None,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.HashIndex(
                        fields=["category"], name="pol_pol_categor_bff87e_hash"
                    )
                ],
            },
        ),
    ]
